### ISSUE TITLE
Question - changing startup mode

### ISSUE THREAD

**Issue by obkram** [fablab-ka/ESP-Matrix#2]
Dear fabian-ka,
at first i love this projekt.

My question:
Is it possible to show a blanc display at startup?
I tried to...

... change in the AllIncludes.h the line:

  unit_t myContent = ownIP;
  to
  unit_t myContent = longtext;

...and...

in the „Display“ the following line

if(0== strlen(_content)) {strcpy(_content, “no text! “, sizof(_content)); }
...to...
if(0== strlen(_content)) {strcpy(_content, “ “, sizof(_content)); }

but it doesn’t work. The ip was still shown at startup. Do You have a better idea?

Thanks

**Comment by wkraft-fablabka** [comment]
Hi,

just add one line as the last line for setup():
`myMatrix.setMode(longtext, "Text to display");`

Without beeing overwritten, the LEDmatrix object initializes with ownIP.

**Comment by obkram** [comment]
Thank you for the answer. I inserted the line..
**myMatrix.setMode(longtext, " ");**
in the ESP matrix and under the line..
**WiFi.begin();**
I don't know if it was correct, but it works. The background is that the matrix doesn't show anything in startup mode. Now I can send a text to a person or room, which can then be terminated after reading via reset button.
Thank you very much for the help.
